### ISSUE TITLE
Two Launching icon problem

### ISSUE THREAD

**Issue by Sekhtech** [lj-3d/GearLoadingProject#2]
Sir, it gives some nice animation but it causes some problems. My app is installed twice whenever I add this library into my project. I think there might be a launcher in your manifest which causes the problem, I am not sure though. I really want to use this library in my project, so please sir, have a look at this problem. Thank you.

**Comment by lj-3d** [comment]
Hi, sorry about thia issue, proceeding to fix it.

3 янв. 2017 г. 7:58 AM пользователь "Shakil Ahmed" <notifications@github.com>
написал:

**Comment by lj-3d** [comment]
Fixed. Try to pull changes and let me know if it works !!

2017-01-03 9:10 GMT+02:00 Любомир Мельник <nfsworld53@gmail.com>:

**Comment by Sekhtech** [comment]
Thank you sir. It is working now..
